#!/bin/bash

echo "
Built for 64-bit Raspberry Pi OS...

   ;d0KOd.  .oOK0x:  
 0xlllcoxolkolllloX 
  ;OccloddKNdxdocckc 
   .dkddkWNNMOdoxd,  
   .o:,x0....xd,ck'  
   K:xOoloOOccloocW  
 .x;N:....xO....'K;k,
 O..Nc...:XNl...:X.,X
 .kkx0NXk'...dNNxldK'
  'k...0o....,O...d: 
   ;o;'oM0olkWc.;oc  
     .cOx....dOl.    
        .x00k.  

GNU/Linux aarch64 5.10.92-v8+

"
sleep 3
echo "Note: After configuration is complete, bluetooth and wifi will be disabled

System will auto-reboot at completion...
"

echo "Getting system info..."
cat /proc/cpuinfo

echo ""
sleep 2
# give permissions to build script (only write is necessary)
sudo chmod 777 builder

################################# enable ssh ###################################

if service ssh status | grep -q inactive; then
    echo "Enabling SSH..."
    ssh-keygen -A &&
    update-rc.d ssh enable &&
    invoke-rc.d ssh start 
else
    echo "SSH is already enabled... Moving on"
fi
######################### Disable Wi-Fi and bluetooth #########################
# disable transmisson capability (persists after reboot, reverse with unblock command)
sudo rfkill block wifi && sudo rfkill block bluetooth

############################# update and ugrade ################################
#  may disable when stable version is complete
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade 

########################### install dependencies ################################
# basic installs
echo "Installing basic packages..."
sudo apt-get install -y whiptail
sudo apt-get install -y figlet
sudo apt-get install -y nmap
sudo apt-get install -y ndiff


# more complicated installs

############################## configurations #####################################
# wake-switch and LED

# network connection LED

# web server

############################## Link files #####################################
# symlinks


############################## Clean up dirs ##################################
# remove unecessary stuff
sudo rm -rf Bookshelf/
sudo rm -rf Documents/
sudo rm -rf Downloads/
sudo rm -rf Music/
sudo rm -rf Pictures/
sudo rm -rf Public/
sudo rm -rf Templates/
sudo rm -rf Videos/

echo " Cleaned out some junk..."
############################## Add dirs ##################################
# make sure we are in the right dir
echo "Adding some directories..."
sudo mkdir -p raspinet/bin && 
sudo mkdir raspinet/discovery &&
sudo mkdir raspinet/discovery/hosts && 
sudo mkdir raspinet/discovery/ports &&
sudo mkdir raspinet/discovery/services
sudo chmod 777 raspinet &&
sudo chmod 777 raspinet/bin &&
sudo chmod 777 raspinet/discovery &&
sudo chmod 777 raspinet/discovery/hosts &&
sudo chmod 777 raspinet/discovery/ports &&
sudo chmod 777 raspinet/discovery/services

#sudo wget https://raw.githubusercontent.com/GaryDeco/Raspinet/main/raspinet/ 

echo "Done"
sleep 1

############################### End of Config ##################################
# final house keeping
echo "Covering tracks..."
sudo rm builder
sleep 1
echo ""
echo "Done"
# reboot the system
echo ""
echo "Installation complete..."
sleep 1
echo "Rebooting..."
sleep 2
sudo reboot
