#!/bin/bash

echo "
Built for...

   ;d0KOd.  .oOK0x:  
 0xlllcoxolkolllloX 
  ;OccloddKNdxdocckc 
   .dkddkWNNMOdoxd,  
   .o:,x0....xd,ck'  
   K:xOoloOOccloocW  
 .x;N:....xO....'K;k,
 O..Nc...:XNl...:X.,X
 .kkx0NXk'...dNNxldK'
  'k...0o....,O...d: 
   ;o;'oM0olkWc.;oc  
     .cOx....dOl.    
        .x00k.  

GNU/Linux aarch64 5.10.92-v8+

"
echo "Note: After configuration is complete, bluetooth and wifi will be disabled

System will auto-reboot at completion...

"
echo "Getting system info..."
cat /proc/cpuinfo

echo ""

# give permissions to build script (only write is necessary)
sudo chmod 777 builder

# enable ssh
if service ssh status | grep -q inactive; then
    echo "Enabling SSH..."
    ssh-keygen -A &&
    update-rc.d ssh enable &&
    invoke-rc.d ssh start &&
else
    echo "SSH is already enabled... Moving on"
fi

# install packages
echo "Installing packages..."

# update and ugrade 
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade 

# install dependencies
sudo apt-get install -y whiptail
sudo apt-get install -y figlet
