#!/bin/bash

# ------------- Under Construction ---------------------#

figlet Kali-Linux-installer
sleep 1
echo "Network Analyzer Project"
sleep 1
echo "

Author: Gary Decosmo
Versiom: 0.0.1b

"

ARCH=$(dpkg --print-architecture)
HOMEDIR=/home/kali

get_os(){
    echo "getting os"
}

get_arch(){
    echo "getting architecture"
}

clean_filesystem(){
    echo "cleaning files in $HOMEDIR" 
}

