#!/bin/bash

###########################################################################################
# Author: Gary Decosmo
# Date created: 2/19/2022
# Updated: 3/10/2022
# Description: Install script for raspinet scanner
# run this script on a fresh install of a raspbian OS to build the scanner enviornment. 

# This script is run with the following commands in the Rpi terminal
# --- Switch to superuser --- #
#$ sudo su
# --- Fetch the build script --- #
#$ wget --no-check-certificate --content-disposition https://raw.githubusercontent.com/Raspinet/main/installer/raspios_buster_armhf
# --- Run the build script --- #
# sudo bash raspios_buster_armhf

# Please add an issue if you encounter a bug
###########################################################################################

function dispMsg() {
    whiptail --title "$1" --msgbox "$2" 10 40
}

################################# SSH ###################################
# --- check is SSH is enabled, if not, install it. 
if service ssh status | grep -q inactive; then
    ssh-keygen -A &&
    update-rc.d ssh enable &&
    invoke-rc.d ssh start 
    spacer 1
    # -------------------------------------------#
    # added to enable root ssh login (3/12/2022)
    #TODO tranfer all fixes to another file
    echo $ROOTSSH >> /etc/ssh/sshd_config
    spacer
    sudo service ssh restart 
fi

######################### Disable Wi-Fi and bluetooth #########################
# disable transmisson capability (persists after reboot, reverse with unblock command)
sudo rfkill block wifi && sudo rfkill block bluetooth # disable wifi and disable bluetooth

############################# update and ugrade ################################
#  may disable when stable version is complete
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade 
sudo apt-get insatll raspi-config 

########################### install dependencies ################################
# basic installs

################################# OS TOOLS #####################################
sudo apt-get install -y whiptail # menu tool
sudo apt-get install -y figlet # pretty display in CLI
sudo apt-get install -y rrdtool # for sampling temperature
sudo apt-get install -y git # ensure git is installed
sudo apt-get install -y curl wget lynx w3m gnupg2 # ensure wget and curl are up to date and add lynx + w3m

# --- Nodejs for web server --- #
sudo curl -fsSL https://deb.nodesource.com/setup_17.x | bash -
sudo apt-get install -y nodejs
# --- python tools --- #
sudo pip install argparse
sudo pip install python-libnmap
sudo apt-get install -y python3-pandas
############################### NETWORK TOOLS ####################################

sudo apt-get install -y nmap # scanning the network
sudo apt-get install -y ndiff # comparing scans
sudo apt-get install -y xsltproc # convert xml to html {added 4/1/2022}
sudo apt-get install -y arp-scan
#sudo apt-get install -y network-manager # {added 4/2/2022}
sudo apt-get install -y pishrink # .img file handling
sudo apt-get install -y gparted # partition handling and resizing

############################## configurations #####################################
#------ Locale -------#
sudo perl -pi -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen
sudo rm /etc/localtime
sudo ln -s /usr/share/zoneinfo/$TZ /etc/localtime
sudo rm /etc/timezone
echo $TZ > /etc/timezone
sudo timedatectl
sudo sed -i 's/XKBMODEL=\"\w*"/XKBMODEL=\"'$KBMODEL'\"/g' /etc/default/keyboard
sudo sed -i 's/XKBLAYOUT=\"\w*"/XKLAYOUT=\"'$KBLAYOUT'\"/g' /etc/default/keyboard
sudo sed -i 's/XKBOPTIONS=\"\w*"/XKBOPTIONS=\"'$KBMODEL'\"/g' /etc/default/keyboard

#TODO complete this config
echo $HOSTNAME > /etc/hostname
#---------------------------------------------------------------#
# hostname was not properly updated to /etc/hosts (3/12/2022)
TODO add this with other fixes to a seperate file
fix_hostname(){
cat << EOF
127.0.0.1     localhost
::1           localhost ip6-localhost ip6-loopback
ff02::1       ip6-allnodes
ff02::2       ip6-allrouters

127.0.0.1     $HOSTNAME
EOF
}
fix_hostname > /etc/hosts
#--------------------------------------------------------------#
sudo mkdir -p /etc/X11/xorg.conf.d/
sudo cp /usr/share/raspi-config/10-blanking.conf /etc/X11/xorg.conf.d/
printf "\\033[9;0]" >> /etc/issue
############################## Link files #####################################
# symlinks #TODO symlinks need to be added

############################## Clean up dirs ##################################

############################## ADDING DIRECTORIES ##################################

############################# SCRIPT INSTALLS ####################################

######################### FILE RELOCATION AND PERMISSIONS #######################

############################### End of Config ##################################
# final house keeping
sudo rm raspios_buster_armhf
# Fix for installer icon
# function fix_icon(){
# sudo chmod 777 /home/dev/Desktop/installer.desktop
# cat << EOF
# [Desktop Entry]
# Name=Installer 
# Comment=RasPiNet Installer Script
# Icon=/home/dev/raspinet/installer/install_icon.png
# Exec=lxterminal -t "RasPiNet Auto-Installer GUI" -e bash /home/dev/raspinet/installer/rpinet_install.sh
# Type=Application
# Encoding=UTF-8
# Terminal=false
# StartupNotify=false
# Categories=None;
# EOF
# }
# fix_icon > /home/dev/Desktop/installer.desktop
# sleep 1
#--------------------------------------------------------------#
if whiptail --title "RasPiNet Installer" --yesno "Do you want to install the metasploit CLI?" 10 40; then
    sudo curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall
    sudo chmod +x msfinstall
    sudo bash msfinstall
    sudo mv msfinstall /home/dev/raspinet/installer/ 
else
    break
fi


# ------------- Adding RPi wake button script from my arcade project -------------- #
git clone https://github.com/GaryDeco/RetroPie-Power-Switch.git
cd RetroPie-Power-Switch/script/
bash install > /dev/null 2>&1
echo
cd /home/dev/raspinet
sudo rm -rf /home/dev/RetroPie-Power-Switch/
#--------------------------------------------------------------#
clear
dispMsg "RasPiNet Installer" "Installation complete"
if whiptail --title "RasPiNet Installer" --yesno "Do you want to reboot now?" 10 40; then
    dispMsg "RasPiNet Installer" "Rebooting..."
    sudo reboot now
else
    dispMsg "RasPiNet Installer" "Exiting..."
    exit
fi
############################### More To-Do's ##################################
#TODO Organize with some functions
#TODO Use flags for better management
#TODO define requirements and dependencies in a seperate file?
#TODO Add LED scripts and GPIO management
